apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watches-eshop
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/clbartolome/watches-eshop
    targetRevision: CHANGE_BRANCH_NAME
    path: app-sets
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: {}