apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: watches-eshop-applications
spec:
  generators:
    - git:
        repoURL: https://gitlab.com/ansible-eda-dynatrace-demo/watches-eshop.git
        revision: master
        files:
          - path: "applications/*.json"
  template:
    metadata:
      name: '{{ app_name }}'
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/ansible-eda-dynatrace-demo/watches-eshop.git
        targetRevision: '{{ argo_config.branch }}'
        path: '{{ argo_config.path }}'
      destination:
        server: '{{ k8s_cluster.address }}'
        namespace: '{{ k8s_cluster.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true