apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: catalog
spec:
  output:
    to:
      kind: ImageStreamTag
      name: catalog-dev:latest
  runPolicy: Serial
  source:
    contextDir: catalog
    git:
      uri: http://@GITEA_HOST_CHANGEME/gitea/watches-eshop-source
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.3
        namespace: openshift
    type: Source
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  triggers: 
  - type: "ConfigChange"
