apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"catalog-db-dev"}]'