apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: gateway
  app.kubernetes.io/component: gateway
  app.kubernetes.io/instance: gateway
  app.kubernetes.io/part-of: watches-eshop
  app.openshift.io/runtime: golang

resources:
- deployment.yaml
- service.yaml
- route.yaml

configMapGenerator:
- name: gateway-configuration
  envs:
  - properties.env

images:
- name: gateway
  newName: quay.io/demo-applications/eshop-gateway
  newTag: 1.0.0