apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalog-build
spec:
  params:
  - name: SOURCE_GIT_URL
    type: string
    description: The application git repository
    default: http://gitea.watches-eshop-cicd.svc.cluster.local:3000/gitea/watches-eshop-source
  - name: SOURCE_GIT_REVISION
    type: string
    description: The application git revision
    default: master
  - name: SOURCE_GIT_CONTEXT_DIR
    type: string
    description: The application path in git
    default: catalog
  - name: MAVEN_MIRROR_URL
    type: string
    description: Maven mirror for Maven Builds
    default: http://nexus.watches-eshop-cicd.svc.cluster.local:8081/repository/maven-all-public/
  - name: NEXUS_URL
    type: string
    description: Maven mirror for Maven Builds
    default: http://nexus.watches-eshop-cicd.svc.cluster.local:8081/repository
  workspaces:
  - name: app-source
  - name: maven-settings
  tasks:
# ------------ CLONE REPOSITORY ------------ #
  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source
# ------------ GENERATE IMAGE TAG ------------ #
  - name: generate-tag
    taskRef:
      kind: Task
      name: generate-tag
# ------------ RUN UNIT TESTS ------------ #
  - name: unit-tests
    runAfter:
    - git-clone
    - generate-tag
    taskRef:
      kind: Task
      name: maven
    params:
    - name: MAVEN_IMAGE
      value: registry.access.redhat.com/ubi8/openjdk-11:1.3
    - name: CONTEXT_DIR
      value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
    - name: GOALS
      value:
      - clean
      - test
    - name: MAVEN_MIRROR_URL
      value: $(params.MAVEN_MIRROR_URL)
    workspaces:
    - name: source
      workspace: app-source
    - name: maven-settings
      workspace: maven-settings
# ------------ Package app ------------ #
  - name: package
    runAfter:
    - unit-tests
    taskRef:
      kind: Task
      name: maven
    params:
    - name: MAVEN_IMAGE
      value: registry.access.redhat.com/ubi8/openjdk-11:1.3
    - name: CONTEXT_DIR
      value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
    - name: GOALS
      value:
      - package
      - -DskipTests
    - name: MAVEN_MIRROR_URL
      value: $(params.MAVEN_MIRROR_URL)
    workspaces:
    - name: source
      workspace: app-source
    - name: maven-settings
      workspace: maven-settings
# ------------ Upload JAR to Nexus ------------ #
  - name: nexus-upload
    runAfter:
    - package
    taskRef:
      kind: Task
      name: maven
    params:
    - name: MAVEN_IMAGE
      value: registry.access.redhat.com/ubi8/openjdk-11:1.3
    - name: CONTEXT_DIR
      value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
    - name: GOALS
      value:
      - deploy
      - -DaltDeploymentRepository=nexus::default::$(params.NEXUS_URL)/maven-releases/
      - -DaltSnapshotDeploymentRepository=nexus::default::$(params.NEXUS_URL)/maven-snapshots/
      - -DskipTests
    - name: MAVEN_MIRROR_URL
      value: $(params.MAVEN_MIRROR_URL)
    workspaces:
    - name: source
      workspace: app-source
    - name: maven-settings
      workspace: maven-settings