apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
- |-
  apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: gateway
  $patch: delete