---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-gpte-gitea
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/gpte-devops-automation/gitea-catalog:latest
  displayName: Red Hat GPTE (Gitea)
  publisher: Red Hat GPTE
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gitea-operator.openshift-operators: ''
  name: gitea-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: redhat-gpte-gitea
  sourceNamespace: openshift-marketplace
  startingCSV: gitea-operator.v1.2.3
---
apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: repository
spec:
  giteaVolumeSize: 1Gi
  giteaImageTag: latest
  postgresqlVolumeSize: 1Gi
  giteaSsl: true
  giteaAdminUser: gitea-admin
  giteaAdminPassword: "r3dh4t1!"
  giteaAdminPasswordLength: "32"
  giteaAdminEmail: admin@example.com