apiVersion: batch/v1
kind: Job
metadata:
  generateName: gitea-setup-
  namespace: watches-eshop-cicd
  name: configure-gitea
  labels:
      app.kubernetes.io/part-of: gitea
      name: configure-gitea
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: git
        image: quay.io/calopezb/git-utils:1.0.0
        env:
        - name: GITEA_HOSTNAME
          value: @GITEA_HOSTNAME
        command:
        - /bin/sh
        - '-c'
        args:
        - |-
          pwd
          mkdir repository
          cd repository
          echo "-- Creating gitea user"
          curl -X POST \
            -d '{"username":"gitea","password":"openshift","retype":"openshift","email":"gitea@gitea.com","send_notify":false}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/user/sign_up

          echo "-- Migrating wathes-eshop-source"
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
            -u gitea:openshift \
            -d '{"clone_addr": "https://github.com/clbartolome/watches-eshop-source", "repo_name": "watches-eshop-source"}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/api/v1/repos/migrate)

          if [ "$RESPONSE" != "201" ]; then
              echo "Error migrating watches-eshop-source repository, error code: $RESPONSE"
              exit 1
          fi

          echo "-- Migrating wathes-eshop"
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
            -u gitea:openshift \
            -d '{"clone_addr": "https://github.com/clbartolome/watches-eshop", "repo_name": "watches-eshop"}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/api/v1/repos/migrate)

          if [ "$RESPONSE" != "201" ]; then
              echo "Error migrating watches-eshop, error code: $RESPONSE"
              exit 1
          fi

          echo "-- Updating GITEA repository host to: http://$GITEA_HOSTNAME"
          git clone http://gitea:openshift@$GITEA_HOSTNAME/gitea/watches-eshop
          cd watches-eshop
          git config user.email "gitea@gitea.com"
          git config user.name "gitea"
          grep -rl "@GITEA_HOSTNAME" resources/argocd/ | xargs sed -i "s/@GITEA_HOSTNAME/$GITEA_HOSTNAME/g"
          grep -rl "@GITEA_HOSTNAME" deploy/ | xargs sed -i "s/@GITEA_HOSTNAME/$GITEA_HOSTNAME/g"
          git add . && git commit -m "Updated Gitea host" && git push
          
          echo "------------------------------"
        imagePullPolicy: Always
      restartPolicy: Never