apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

nameSuffix: -prod

commonLabels:
  app: catalog-prod
  app.kubernetes.io/component: catalog-prod
  app.kubernetes.io/instance: catalog-prod
  app.kubernetes.io/part-of: watches-eshop-prod

patches:
- ./deployment.yaml

configMapGenerator:
- name: catalog-configuration
  envs:
  - properties.env

secretGenerator:
- name: catalog-secured-configuration
  envs:
  - secured.env

images:
- name: catalog
  newName: image-registry.openshift-image-registry.svc:5000/watches-eshop-dev/catalog-dev
  newTag: latest