apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: payment
  app.kubernetes.io/component: payment
  app.kubernetes.io/instance: payment
  app.kubernetes.io/part-of: watches-eshop
  app.openshift.io/runtime: nodejs

resources:
- deployment.yaml
- service.yaml
- route.yaml

configMapGenerator:
- name: payment-configuration
  envs:
  - properties.env

secretGenerator:
- name: payment-secured-configuration
  envs:
  - secured.env

images:
- name: payment
  newName: quay.io/ansible_eda/payment
  newTag: 1.0.0