apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: catalog-build
  generateName: catalog-build-run
spec:
  pipelineRef:
    name: catalog-build
  serviceAccountName: pipeline
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  - name: maven-settings
    configmap:
      name: maven-settings