apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: catalog
  version: v1
  app.kubernetes.io/component: catalog
  app.kubernetes.io/instance: catalog
  app.kubernetes.io/name: ubi8-openjdk-11
  app.kubernetes.io/part-of: watches-eshop
  app.openshift.io/runtime: spring-boot

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: catalog-configuration
  envs:
  - properties.env

secretGenerator:
- name: catalog-secured-configuration
  envs:
  - secured.env

images:
- name: catalog
  newName: quay.io/demo-applications/eshop-catalog
  newTag: 1.0.0