apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- buildConfig.yaml
- imageStream.yaml

nameSuffix: -dev

commonLabels:
  app: eshop-ui-dev
  app.kubernetes.io/component: eshop-ui-dev
  app.kubernetes.io/instance: eshop-ui-dev
  app.kubernetes.io/part-of: watches-eshop-dev

patches:
- ./deployment.yaml

configMapGenerator:
- name: eshop-ui-configuration
  envs:
  - properties.env

secretGenerator:
- name: eshop-ui-secured-configuration
  envs:
  - secured.env

images:
- name: eshop-ui
  newName: image-registry.openshift-image-registry.svc:5000/watches-eshop-dev/eshop-ui-dev
  newTag: latest