apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ubi8-openjdk-11
  app.openshift.io/runtime: spring-boot

resources:
- deployment.yaml
- service.yaml
- route.yaml