apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: eshop-ui
  version: v1
  app.kubernetes.io/component: eshop-ui
  app.kubernetes.io/instance: eshop-ui
  app.kubernetes.io/part-of: watches-eshop
  app.openshift.io/runtime: nginx

resources:
- deployment.yaml
- service.yaml
- route.yaml

configMapGenerator:
- name: eshop-config
  files:
  - config.json

images:
- name: eshop-ui
  newName: quay.io/demo-applications/eshop-ui
  newTag: 1.0.0